ITEM.name = "MK3A2 Grenade"
ITEM.description = "A throwable explosive to flush out opponents."
ITEM.model = "models/weapons/w_grenade.mdl"
ITEM.class = "weapon_frag"
ITEM.weaponCategory = "grenade"
ITEM.classes = {CLASS_EOW}
ITEM.flag = "g"
ITEM.width = 1
ITEM.height = 1